### ISSUE TITLE
Geocoding

### ISSUE THREAD

**Issue by rosskevin** [code-and-effect/effective_addresses#11]
@matt-riemer are you interested in optional geocoding if I submit a pull?  Or should I just keep that in my codebase?

https://github.com/alexreisner/geocoder

**Comment by rosskevin** [comment]
Looking at this now, it looks like would be best as optionally integrated, it could affect the form helpers, address building etc.  e.g. `pre_selected_country` and `pre_selected_state`

I'll put it together and we can go from there.

**Comment by matt-riemer** [comment]
I'm open to the geocoding PR...I agree it would make sense as a config option.

I know a lot of the geocode services limit the number of API requests you can make...if someone is dealing with 10,000 addresses, they may have issues geocoding all at once!

**Comment by rosskevin** [comment]
@matt-riemer just submitted PR #12, it just does a bunch of conveniences on IP based preselection.

I've added a sample config as well to suggest caching and eliminate most calls.  I haven't added actual geocoding to the model yet, though I may get to that.  Certainly the Geocoder gem seems to be a good choice for that.
