### ISSUE TITLE
Missing partial effective/addresses/_address_fields_simple_form

### ISSUE THREAD

**Issue by stepankuzmin** [code-and-effect/effective_addresses#16]
I'm getting `Missing partial effective/addresses/_address_fields_simple_form` error then trying to display SimpleForm example:
```ruby
= simple_form_for @user do |f|
  %h3 Billing Address
  = effective_address_fields(f, :billing_address)

  = f.submit 'Save'
```

I think it should be documented how to create partials for this gem.

**Comment by matt-riemer** [comment]
Hey @stepankuzmin 

Thanks for your interest in effective_addresses! :)

This is a weird error....I wouldn't expect a partial that is present in the gem to be missing!

You can, as with any Rails gem, override an existing partial by putting your own in the `app/views/effective/addresses/` directory.  But the packaged partial with the gem should be present.

Did you run the `bundle exec effective_addresses:install` task?  Do you have a `app/config/initializers/effective_addresses.rb` file?  Does that run properly? :)

Thanks!
