### ISSUE TITLE
undefined method `acts_as_addressable' for Order (call 'Order.connection' to establish a connection):Class

### ISSUE THREAD

**Issue by benjaminb10** [code-and-effect/effective_addresses#21]
I have an Order model. I have followed installation instructions, add the line `  acts_as_addressable :billing
` to my Order model and run db:migrate, but I have this issue:

> undefined method `acts_as_addressable' for Order (call 'Order.connection' to establish a connection):Class

How to specify to my Order model that I have a billing_address? Should I use the has_one method?

**Comment by matt-riemer** [comment]
Hey great question!

It sounds like your app doesn't know about `acts_as_addressable`.

Do you have the `config/initializers/effective_address.rb` present, does that run?

What rails version are you running?

**Comment by benjaminb10** [comment]
I've just relaunch server. Sorry.
