### ISSUE TITLE
Error when submitting form

### ISSUE THREAD

**Issue by benjaminb10** [code-and-effect/effective_addresses#23]
Hi, when I submit form, I always have this errors:

> 2 errors prohibited this order from being saved:
> Addresses addressable must exist
> Billing address is invalid

In my view:
`              <%= effective_address_fields(form, :billing_address, :field_order => [:country_code, :full_name, :address1, :address2, :city, :state_code, :postal_code]) %>
`

In my controller I've add accept_params as the documentation
In my model I've   `acts_as_addressable :billing`

Any clue?

**Comment by benjaminb10** [comment]
Do I have to add a foreign_key to my Model?

**Comment by matt-riemer** [comment]
No, you shouldn't have to add any foreign_keys...

Can I see a snippet of your model and your form?

If you stopped and did `binding.pry` in your view somewhere, after the form saved but came back with errors, what's your `f.object.errors` look like?

Try to simplify! I feel like there must be something in your base model invalid somewhere

**Comment by matt-riemer** [comment]
Are there any unpermitted params?
