### ISSUE TITLE
Add custom fields like contact phone number

### ISSUE THREAD

**Issue by benjaminb10** [code-and-effect/effective_addresses#24]
Is there a way of adding custom fields like contact phone number?

**Comment by matt-riemer** [comment]
Nope.  Just address fields.

You might want to implement your own address model & form then, but you could still use the province and country select ability for this gem or checkout `carmen-rails`gem, which this relies on anyway :)

**Comment by benjaminb10** [comment]
Since you have an optional fullname field, adding custom other fields can be helpful in some usecases.
