### ISSUE TITLE
Readme instructions fail on rails generate (inside another engine)

### ISSUE THREAD

**Issue by rosskevin** [code-and-effect/effective_addresses#6]
1. add gem
2. `bundle install`
3. `rails generate effective_addresses:install`

```ruby
      create  config/initializers/effective_addresses.rb
/Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/effective_addresses-1.2.2/lib/generators/effective_addresses/install_generator.rb:23:in `create_migration_file': undefined method `addresses_table_name' for EffectiveAddresses:Module (NoMethodError)
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/railties-4.2.3/lib/rails/generators.rb:157:in `invoke'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/railties-4.2.3/lib/rails/commands/generate.rb:13:in `<top (required)>'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

Not a big deal, just wanted to note that the happy path for getting started isn't working.

**Comment by rosskevin** [comment]
Could be due to it being a `dummy

**Comment by rosskevin** [comment]
So the only optional change to the instructions would be
1. add gem
2. bundle install
3. (optional) require gem if inside an engine
4. generate

Feel free to close, perhaps an unusual situation.

**Comment by matt-riemer** [comment]
hey @rosskevin :)

Thanks for your interest in effective_addresses!  I spent time building out addresses as a has_many in multiple rails apps, and decided to make a gem out of the pattern.  It was one of the first gems I wrote.

I've been using effective_addresses for a long time, and it's pretty good! 

The easy integration with Carmen is and it mostly just works with simple form.

Are you implementing effective_addresses inside an engine?  What are you building? :)

You might wanna check out effective_orders, where I implement effective_addresses inside an engine.  Sure enough:

https://github.com/code-and-effect/effective_orders/blob/15a610d33e2943fc9a36e276c593a0cc4f6aa568/lib/effective_orders.rb#L1

Line 1, I require 'effective_addresses' :)

I'll update the documentation accordingly.  

Thanks!

**Comment by rosskevin** [comment]
@matt-riemer we are implementing an engine which is our general purpose foundation for several products.  This includes commerce documents (invoice, bill, payment, credit note, sales order) with parallel double entry accounting, tax determination integration and customization, and a versatile multi-party subscription/recurrence model that can be used with any payment provider.  

I needed historical addresses, which is why I looked here. I've already integrated but need to test the front end tomorrow.  For the most part our existing model swapped out for what you have.  Some differences I'll need to see how it goes:

- we use bower and coffeescript for js assets
- we have front end validation (coffeescript) based on rails models (similar to client_side_validations but with full separation of requirements from rails represented as json hash, and front end coffeescript interpretation/integration/implementation with formvalidation.io)
- we use the html `%address` element in markup for browser conveniences

I'll see how it goes and submit back my edits if they are generally useful enhancements.

**Comment by matt-riemer** [comment]
Ooh business software :)

Hehe..yea, I write a ton of business apps, and have done a lot of those
projects, but in pieces.

I hope your team can keep that huge scope in check...for one app, adding
the account stuff and tax is so big too. Good luck!!

I had never run into formvalidatio.io before, it looks really nice.  mmm
sexy forms

They need to tie it into the simple_form toolchain, so everything is a
one-liner


I don't remember if effective_addresses outputs a %div or an %address...it
just calls simple_form or formtastic.

But I hope it works out for you and can save some time.  It will definitely
handle the current and historic addresses easily.

Any code is welcome!

Thanks

--
Matt Riemer
Senior Developer, AgileStyle
agilestyle.com  |  #204 8540 109st Edmonton AB T6G 1E6
