### ISSUE TITLE
"Please choose a country first" with priority country

### ISSUE THREAD

**Issue by rosskevin** [code-and-effect/effective_addresses#8]
![pre-selected-country](https://cloud.githubusercontent.com/assets/136564/9233557/5f6dd104-40f9-11e5-8e07-2ead63ca07bd.png)
On load of a blank form (simple_form), even though a priority country is loaded and  the state options are present in the list, the selection states `Please choose a country first` which is misleading.

Perhaps on load of a country, this option should switch to blank, be removed, or say `Please choose a state`

**Comment by rosskevin** [comment]
I'll take a shot at this one since it is readily reproducible for me.

**Comment by rosskevin** [comment]
Pull request #9 solves this

**Comment by matt-riemer** [comment]
Another great refactor, this is great, thank you!

I have released effective_addresses 1.2.4 with both your PRs merged.
